//
// Asset.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Token detail in the transaction */
public struct Asset: Codable {
    public var tokenId: String
    public var amount: Int64
}
