//
// ErgoTransactionDataInput.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct ErgoTransactionDataInput: Codable {


    public var boxId: TransactionBoxId
        
}       
