//
// ErgoTransactionInput.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct ErgoTransactionInput: Codable {
    public var boxId: String
    public var spendingProof: SpendingProof
}
