//
// ErgoAddress.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Encoded Ergo Address */
public struct ErgoAddress: Codable {


}
