//
// NodeInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct NodeInfo: Codable {

    public enum StateType: String, Codable {
        case digest = "digest"
        case utxo = "utxo"
    }
    public var currentTime: UInt64?
    public var name: String
    public var appVersion: String
    public var fullHeight: UInt64?
    public var headersHeight: UInt64?
    public var bestFullHeaderId: String?
    public var previousFullHeaderId: String?
    public var bestHeaderId: String?
    public var stateRoot: String?
    public var stateType: StateType?
    public var stateVersion: String?
    public var peersCount: Int?
    public var unconfirmedCount: Int?
    public var difficulty: UInt64?
    public var launchTime: UInt64?
    public var headersScore: Decimal?
    public var fullBlocksScore: Decimal?
    public var genesisBlockId: String?
    public var parameters: Parameters?
    public var isMining: Bool?

    public init() {
        self.name = "Test node"
        self.appVersion = "3.2.0"
        self.fullHeight = 100
        self.headersHeight = 100
    }
    public init(name: String, appVersion: String, fullHeight: UInt64, headersHeight: UInt64) {
        self.name = name
        self.appVersion = appVersion
        self.fullHeight = fullHeight
        self.headersHeight = headersHeight
    }
    public init(name: String, appVersion: String, fullHeight: UInt64, headersHeight: UInt64, bestFullHeaderId: String, previousFullHeaderId: String, bestHeaderId: String, stateRoot: String, stateType: StateType, stateVersion: String, isMining: Bool, peersCount: Int, unconfirmedCount: Int, difficulty: UInt64, currentTime: UInt64, launchTime: UInt64, headersScore: Decimal, fullBlocksScore: Decimal, genesisBlockId: String, parameters: Parameters) {
        self.name = name
        self.appVersion = appVersion
        self.fullHeight = fullHeight
        self.headersHeight = headersHeight
        self.bestFullHeaderId = bestFullHeaderId
        self.previousFullHeaderId = previousFullHeaderId
        self.bestHeaderId = bestHeaderId
        self.stateRoot = stateRoot
        self.stateType = stateType
        self.stateVersion = stateVersion
        self.isMining = isMining
        self.peersCount = peersCount
        self.unconfirmedCount = unconfirmedCount
        self.difficulty = difficulty
        self.currentTime = currentTime
        self.launchTime = launchTime
        self.headersScore = headersScore
        self.fullBlocksScore = fullBlocksScore
        self.genesisBlockId = genesisBlockId
        self.parameters = parameters
    }

}
