//
// TransactionBoxId.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Base16-encoded transaction box id bytes. Should be 32 bytes long */
public struct TransactionBoxId: Codable {


}
