//
// ErgoTree.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Base16-encoded ergo tree bytes */
public struct ErgoTree: Codable {


}   
