//
// NodeInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct NodeInfo: Codable {

    public enum StateType: String, Codable {
        case digest = "digest"
        case utxo = "utxo"
    }

    public var name: String
    public var appVersion: String
    public var fullHeight: Int
    public var headersHeight: Int
    public var bestFullHeaderId: String
    public var previousFullHeaderId: String
    public var bestHeaderId: String
    public var stateRoot: String
    public var stateType: StateType
    public var stateVersion: String
    public var isMining: Bool
    public var peersCount: Int
    public var unconfirmedCount: Int
    public var difficulty: Int
    public var currentTime: Int
    public var launchTime: Int
    public var headersScore: Int
    public var fullBlocksScore: Int
    public var genesisBlockId: String
    public var parameters: Parameters
    public init(name: String, appVersion: String, fullHeight: Int, headersHeight: Int, bestFullHeaderId: String, previousFullHeaderId: String, bestHeaderId: String, stateRoot: String, stateType: StateType, stateVersion: String, isMining: Bool, peersCount: Int, unconfirmedCount: Int, difficulty: Int, currentTime: Int, launchTime: Int, headersScore: Int, fullBlocksScore: Int, genesisBlockId: String, parameters: Parameters) {
        self.name = name
        self.appVersion = appVersion
        self.fullHeight = fullHeight
        self.headersHeight = headersHeight
        self.bestFullHeaderId = bestFullHeaderId
        self.previousFullHeaderId = previousFullHeaderId
        self.bestHeaderId = bestHeaderId
        self.stateRoot = stateRoot
        self.stateType = stateType
        self.stateVersion = stateVersion
        self.isMining = isMining
        self.peersCount = peersCount
        self.unconfirmedCount = unconfirmedCount
        self.difficulty = difficulty
        self.currentTime = currentTime
        self.launchTime = launchTime
        self.headersScore = headersScore
        self.fullBlocksScore = fullBlocksScore
        self.genesisBlockId = genesisBlockId
        self.parameters = parameters
    }

}
