//
// TransactionId.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Base16-encoded transaction id bytes */
public struct TransactionId: Codable {


}
