//
// Digest32.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Base16-encoded 32 byte digest */
public struct Digest32: Codable {


}
