//
// ErgoTransactionOutput.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct ErgoTransactionOutput: Codable {

    public var boxId: String?
    public var value: Int64
    public var ergoTree: String
    public var creationHeight: Int
    public var address: String
    public var assets: [Asset]?
//    public var additionalRegisters: Registers?
    public var transactionId: String?
    public var index: Int?
}
