//
// SpendingProof.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Spending proof for transaction input */
public struct SpendingProof: Codable {


    public var proofBytes: String

    /** Variables to be put into context */
    public var _extension: [String:String]
    public init(proofBytes: String, _extension: [String:String]) {
        self.proofBytes = proofBytes
        self._extension = _extension
    }
    public enum CodingKeys: String, CodingKey {
        case proofBytes
        case _extension = "extension"
    }

}
