//
// SpendingProofBytes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Base16-encoded spending proofs */
public struct SpendingProofBytes: Codable {


}   
